### ISSUE TITLE
DCP Online

### ISSUE THREAD

**Issue by Ar3lzy** [mtcuison/GhostRider-Android#327]
1. UI - Revision ng mga guides sa may additional menu sa collection list (...)
2. Add Collection - di makapag search ng client (Value <br of type java.lang.String cannot be converted to JSONObject)
3. Posting - a. after posting may mga naiiwan pang account number at transaction. ex (uncooperative, did not pay, customer not around)
			 b. nakakapag post before mag remit
4. Data - yung paid transaction lang ang nag aappear. after posting other transactions will be entered as NV - Not Visited

**Comment by kpdumaguin** [comment]
> 1. UI - Revision ng mga guides sa may additional menu sa collection list (...)
> 2. Add Collection - di makapag search ng client (Value <br of type java.lang.String cannot be converted to JSONObject)
> 3. Posting - a. after posting may mga naiiwan pang account number at transaction. ex (uncooperative, did not pay, customer not around)
>    b. nakakapag post before mag remit



> 1. UI - Revision ng mga guides sa may additional menu sa collection list (...)
> 2. Add Collection - di makapag search ng client (Value <br of type java.lang.String cannot be converted to JSONObject)
> 3. Posting - a. after posting may mga naiiwan pang account number at transaction. ex (uncooperative, did not pay, customer not around)
>    b. nakakapag post before mag remit

Sir @mikegarcia8748 
• Regarding doon sa issue no. 2, lumalabas yung error sa test mode, pag sa live hindi.
• Doon naman sa pagdisplay ng search result sa adding ng collection, hindi niya sinasama yung account number sa display pati na rin pagka iddownload.
![1](https://user-images.githubusercontent.com/76087620/159825055-9bc2431d-75cd-4caf-aadf-f38d43bce380.PNG)

• May times din na pag nagssearch ng client, ito yung lumalabas na result sa dialog:
![2](https://user-images.githubusercontent.com/76087620/159825390-fcc7054f-1071-4e74-98c9-c15deb22508d.PNG)
Ito yung error niya:
![2 1](https://user-images.githubusercontent.com/76087620/159825431-4511cd38-5950-4326-be69-6fbb313a457f.PNG)

**Comment by mikegarcia8748** [comment]
API returns JSONObject success result with details as JSONArray pero may undefined variable minsan at null pointer exception sa mismong PHP File.

Ung validation sa Posting na hindi pa nakakapag remit naidagdag ko na sa #328 pull request @kpdumaguin @Ar3lzy

**Comment by mikegarcia8748** [comment]
Changes has been made for fixing reported bugs in this issue.
A new compile apk will be release for 
@Ar3lzy Close this issue if latest compile apk tested has already fix the issue.

**Comment by Ar3lzy** [comment]
03-25-2022

GRider - DCP Online

1. UI - Revision ng mga guides sa may additional menu sa collection list (...)
2. Posting - a. after posting may mga naiiwan pang account number at transaction. ex (loan unit, transferred/assume, false ownership)
			 b. nakakapag post before mag remit
3. Data - di nagrereflect yung entry ng paid transaction.

**Comment by mikegarcia8748** [comment]
@kpdumaguin pakirevise nalang ung UI dun sa instructions panel before magopen ung mismong dialog.
dina kasi akma ung nasa instruction at ung actual UI if dipa magawa ngayon, pakitest nalang ung current, Fix na ung issues sa last PUSH ko

**Comment by Ar3lzy** [comment]
03-28-2022
GRider - DCP Online

1. Remitance - check payment - di nagpproceed kahit naka declare na yung account number, eto pa rin ang nagpapakita "please enter account no"
1. Posting - nakakapag post before mag remit

**Comment by Ar3lzy** [comment]
03-30-2022
GRider - DCP Online

1. Posting - after posting may mga naiiwan pang account number at transaction. ex (customer not around)

**Comment by Ar3lzy** [comment]
04-01-2022
GRider - DCP Online

Posting - after posting may mga naiiwan pang account number at transaction. ex (loan unit, transferred/assumed, false ownership)

**Comment by mikegarcia8748** [comment]
All concerns in this issue has been fix according to the final test conducted by sir Rowel. @Ar3lzy 
Code has been merge to Developer Branch #340 along with other bug fix on services.
