### ISSUE TITLE
Selfie Log Adjustment

### ISSUE THREAD

**Issue by mikegarcia8748** [mtcuison/GhostRider-Android#350]
Selfie Log Adjustment:
Add BranchCd for employees who will use the Selfie Log
Allow users to select which branch will be use for Selfie Log
Set reporting branch as selected default branch for selfie log.

Account Adjustments:
Add new status for Selfie Log is user is allowed to use the selfie log feature.
Android Object(Navigation Menus) adjustment, Selfie Log will be shown if user is allowed.

Random Stock Inventory must be shown only for Motorcycle Branches after Cashcount entry.

Adjust create account UI from stationary layout to scrollable.

**Comment by mikegarcia8748** [comment]
All concerns above has been adjusted and tested by programmer.

**Comment by mikegarcia8748** [comment]
Null value for BranchCd under Selfie Log has been adjusted to API.
Allow users to take a Selfie Log Twice with the same BranchCd.
Automatically finish Random Stock Inventory After successfull posting.

**Comment by Ar3lzy** [comment]
Add BranchCd for employees who will use the Selfie Log - OK
Allow users to select which branch will be use for Selfie Log - OK
Set reporting branch as selected default branch for selfie log.	- OK
Add new status for Selfie Log is user is allowed to use the selfie log feature. - OK
Android Object(Navigation Menus) adjustment, Selfie Log will be shown if user is allowed. - OK
Random Stock Inventory must be shown only for Motorcycle Branches after Cashcount entry. - OK
Adjust create account UI from stationary layout to scrollable - OK
Allow users to take a Selfie Log Twice with the same BranchCd. - NOT OK
Automatically finish Random Stock Inventory After successfull posting. NOT OK
Null value for BranchCd under Selfie Log has been adjusted to API. - OK
