### ISSUE TITLE
Daily Collection Plan	

### ISSUE THREAD

**Issue by mnv121** [mtcuison/GhostRider-Android#362]
1. Add collection di nag add /minsan loading lng
2.Transaction log - 
a.# cash on hand alway P0 hnd nalalagyan ng amount pag my paid sa collection list
a.1# unavail to post pleasee remit cash payment before posting
a.2# pag nag remit ng sobra kahit 0 ung cashonhand naleless parin ung total amount
a.3# pwedeng mag remit kahit negative na cashonhand 
b.# Promise to pay Remarks code
b.1 Selfie Login Message of *Please enter the branch* after taking picture
#none so far
@mikegarcia8748 
Reference picture
![a 2](https://user-images.githubusercontent.com/97944690/201295880-680a6434-db03-4765-833a-34f8cd5c51f5.jpg)
![b 2](https://user-images.githubusercontent.com/97944690/201300086-a9408723-7a77-4429-b60f-9e1e6ffede95.jpg)

**Comment by mikegarcia8748** [comment]
Cause of dcp bug found.
Solution: wrong data type has been use for handling amounts.
