### ISSUE TITLE
DCP Add Collection

### ISSUE THREAD

**Issue by szirabanal** [mtcuison/GhostRider-Android#366]
Collection List
Unable to add client on collection list

**Comment by mikegarcia8748** [comment]
new apk compiled for testing available at 10.22/apps/gCircle.apk

**Comment by mnv121** [comment]
**DCP add collection**

>a1# wrong label, Account number into Name 
>a2# pag ka click ng confirm na error value<br type of java.lang.String cannot be converted to JSONObject

**Comment by mikegarcia8748** [comment]
> **DCP add collection**
> 
> > a1# wrong label, Account number into Name
> > a2# pag ka click ng confirm na error value<br type of java.lang.String cannot be converted to JSONObject

Fixed na ung a1# tapos nagdagdag ng extra note para di mali mali ilagay na pangalan ni collector
![image](https://user-images.githubusercontent.com/76087753/208017989-d9403ee9-1d41-4f8f-a4c9-722953f1263e.png)

a2# sa 141 lang hindi working, pero working sa 240 dahil sa API nagkakaerror sa 141
