### ISSUE TITLE
Ghostrider Leave/Business Trip Application / approval

### ISSUE THREAD

**Issue by mnv121** [mtcuison/GhostRider-Android#369]
**Leave Approvals **

> a.1# hnd makita /madownload entry (141) /(ok in .240)
>a.2# Dissapprove button. nag rerequire ng value ng With or With/out pay . (.240)
>a.3# Message box after approval 'message lng nakalagay'(.240)
> 

**Business Trip Approvals **

> a.1# hnd makita /madownload entry

**Comment by mnv121** [comment]
**Leave Approvals **
a.3# Message box after approval 'message lng nakalagay'(.240)/ Testing data (.15)
**Business Trip Approvals **

a.1# hnd makita /madownload entry

**Comment by mikegarcia8748** [comment]
Fixed for this issue has been deployed at Build Version v2.13.046b on Google Playstore
