### ISSUE TITLE
Area Head Selfie Log

### ISSUE THREAD

**Issue by mtcuison** [mtcuison/GhostRider-Android#371]
Target: December 15, 2022

Option not to select branch
   -use reporting branch code
   -do not require cash count and random stock inventory

Initial Screen
Take Selfie
   sBranchCd = ''
   if sBranchCd <> '' AND xAreaCode = sAreaCode Then
         require cash count and random stock inventory
   else
         do not require cash count and random stock inventory
         sBranchCd = reporting branch    
  end if

**Comment by szirabanal** [comment]
is it possible to add remarks column?
for the record if where and what is the purpose or reason for using the selfie log only.
Thanks

**Comment by mikegarcia8748** [comment]
**Selfie Log for AH has been adjusted.** 

New:
DialogSelfieLogRemarks - a dialog that will be promp to user if selected branch is not included in area.

**Comment by mikegarcia8748** [comment]
Okay na po ung Remarks Entry sa selfie log.
Add parameter 'sRemarksx' nalang sa API ng submit selfie log at alter table nalang magsave sa table ung remarks ni AH

![image](https://user-images.githubusercontent.com/76087753/207488910-403dc419-e3bb-4575-a57e-783c7b13a066.png)

selfie log remarks

![image](https://user-images.githubusercontent.com/76087753/207488958-3a83d123-721f-4d21-969a-45c473f2837e.png)

**Comment by mikegarcia8748** [comment]
Nabaliktad ung validation ung user level before ung value ng branchcode kaya nagkaroon ng nullpointer error.

chinecheck ko muna kasi kung AreaManager ung user before mag validate sa pag entry ng remarks

**Comment by mikegarcia8748** [comment]
binalik ko nalang ung default  initialization ng branch code once na nagopen ung selfie log.

**Comment by szirabanal** [comment]
No branch selected.
cancel branch selection, then tap take selfie.
Nagproceed siya sa cash count.

Okay na sa replicationlog na table. nagsasave na siya

![318341693_526808526043128_3179914508736744450_n](https://user-images.githubusercontent.com/119280428/207765884-ed664eac-c5d0-44e8-806b-9bae91e82c6e.jpg)

**Comment by mikegarcia8748** [comment]
Hindi ko pa pala nasasama sa update ung additional validation para sa mga xtreme branches na hawak ni Sir Richard.

**Comment by mikegarcia8748** [comment]
Cash Count Error has been fixed on new branch with the issue #375

**Comment by mikegarcia8748** [comment]
uploading image minsan wrong spelling ung nirereturn na result kaya nag eerror

Error:
![image](https://user-images.githubusercontent.com/76087753/209050741-d021a4fb-402c-49c3-a582-a77885f8362d.png)

Cause:
![image](https://user-images.githubusercontent.com/76087753/209050758-69c09b1a-d978-4600-9bc7-f9312c3e4631.png)

**Comment by mikegarcia8748** [comment]
Solution: request new access token kahit dipa expired ung current access token for uploading
