### ISSUE TITLE
Cash Count Remarks

### ISSUE THREAD

**Issue by mikegarcia8748** [mtcuison/GhostRider-Android#373]
Add remarks on every cash count entry.

![image](https://user-images.githubusercontent.com/76087753/207793308-6f5b15b1-6179-4f9b-9aff-c0fd3920e308.png)

**Comment by szirabanal** [comment]
@mikegarcia8748 

hallo, follow up this concern  for AH request.
"Add remarks on every cash count entry."

ito nalang ung kulang para marelease antin selfie log ng mga AH..
TIA

**Comment by mikegarcia8748** [comment]
Update for this issue has been deployed at Build Version v2.13.046b
