### ISSUE TITLE
Dashboard for Branch Head

### ISSUE THREAD

**Issue by mikegarcia8748** [mtcuison/GhostRider-Android#399]
Create a dashboard for Branch Head which will display the following:

1. Home Page - which has the performance overview of the branch.
2. Panalo Page - which will display Raffle Draw notifications and Rewards.
3. Notifications Page - which will display List of notifications.

**Comment by jeitee** [comment]
done Except displaying of raffle draw notification, and list of raffle draw participants

**Comment by jeitee** [comment]
DONE
