### ISSUE TITLE
Dashboard for Area Head

### ISSUE THREAD

**Issue by mikegarcia8748** [mtcuison/GhostRider-Android#400]
Create a Dashboard for Area Head which will display the following:

1. Home Page -display Branch Opening and Area Performance Monitor
2. Selfie Log Page - display selfie log feature page.
3. Panalo Page - display Panalo Page with Raffle Draw Notification and Rewards.
4. Area Performance Monitoring Page - preview of area performance.
5. Notifications Page - List of notifications

**Comment by jeitee** [comment]
done Except displaying of raffle draw notification, and list of raffle draw participants

**Comment by mikegarcia8748** [comment]
idagdag mo ung retrieval ng GetAllUnreadNotificationCount sa ViewModel nito tapos idagdag mo narin sa controller.

**Comment by jeitee** [comment]
done
