### ISSUE TITLE
Application Search

### ISSUE THREAD

**Issue by mikegarcia8748** [mtcuison/GhostRider-Android#412]
Search using employee name on employee leave and ob applications for approval.

**Comment by ggutoman** [comment]
saan po makikita ang class nito sir? @mikegarcia8748

**Comment by mikegarcia8748** [comment]
![image](https://user-images.githubusercontent.com/76087753/229462971-9e538129-7d72-4431-b0ab-fa8fad8a5d10.png)
Create ka ng Activity_EmployeeApplicationSearch.

Gamit ka ng MaterialToolbar, SearchView, at Recyclerview @ggutoman
