### ISSUE TITLE
Dialog_Mechanics

### ISSUE THREAD

**Issue by mikegarcia8748** [mtcuison/GhostRider-Android#434]
Gumawa ng dialog para i-preview kung paano makakapag participate ang mga employee at kung ano ang mga posibleng premyo sa raffle.

**Comment by jeitee** [comment]
UI is already done!

**Comment by mikegarcia8748** [comment]
Wala pang functions ung dialog, inimplement ko na ung design galing marketing, lagyan mo nalang ng mga functions para magshow at magdismiss.

Ung textview dapat pwede magset ng value @jeitee

**Comment by mikegarcia8748** [comment]
Okay na
