### ISSUE TITLE
Activity_BranchPerformanceMonitoring

### ISSUE THREAD

**Issue by mikegarcia8748** [mtcuison/GhostRider-Android#438]
Create an activity to display detailed mc sales, sp sales, and job order or current branch.

**Comment by jeitee** [comment]
done for the previews of mc sales, sp sales and job order with line chart

**Comment by mikegarcia8748** [comment]
I-center mo ung gravity ng mga textfield sa 
Adapter_Branch_Performance_Monitoring

iparse mo ung displaying ng period sa Adapter_Area_Performance_Monitoring gamitin mo nalang itong method PerformancePeriod.getPeriodText

initialize mo nalang din ung toolbar sa Activity_BranchPerformanceMonitoring
ipareho mo nalang sa initialization ng toolbar ng Activity_AreaPerformanceMonitoring

**Comment by mikegarcia8748** [comment]
Area Performance for Previous 12 Months 
Current Branches Performance

Palitan mo ung mga label sa area performance periodic list at branch performances

**Comment by jeitee** [comment]
done

**Comment by jeitee** [comment]
done ->

I-center mo ung gravity ng mga textfield sa
Adapter_Branch_Performance_Monitoring

iparse mo ung displaying ng period sa Adapter_Area_Performance_Monitoring gamitin mo nalang itong method PerformancePeriod.getPeriodText

initialize mo nalang din ung toolbar sa Activity_BranchPerformanceMonitoring
ipareho mo nalang sa initialization ng toolbar ng Activity_AreaPerformanceMonitoring
