### ISSUE TITLE
Activity_AreaPerformanceMonitoring

### ISSUE THREAD

**Issue by mikegarcia8748** [mtcuison/GhostRider-Android#439]
Create activity to display detailed preview of mc sales, sp sales, and job order of current area

**Comment by mikegarcia8748** [comment]
@jeitee 

**PieChart**

- GetCurrentMCSalesPerformance
- GetCurentSPSalesPerformance
- GetJobOrderPerformance

**LineChart**

- GetMCSalesPeriodicPerformance
- GetSPSalesPeriodicPerformance
- GetJobOrderPeriodicPerformance

methods nasa AreaPerformance Class lahat.

**may dalawang recyclerview sa ibaba ng linechart.**
recyclerview_area_performance 
- dito mo ilagay ung value ng mga:

1. GetMCSalesPeriodicPerformance
2. GetSPSalesPeriodicPerformance
3. GetJobOrderPeriodicPerformance

recyclerview_branches_performance
- dito mo ilagay ung value ng mga:

1. GetMCSalesBranchesPerformance
2. GetSPSalesBranchesPerformance
3. GetJobOrderBranchesPerformance

**Comment by jeitee** [comment]
Display of pie chart and line chart with tab layout
display of recycle view for area and branch performance with tab layout

**Comment by jeitee** [comment]
fix display of line chart base from the recycler view.
Remove class that is not being used in viewmodel.
