### ISSUE TITLE
Activity_BranchList

### ISSUE THREAD

**Issue by mikegarcia8748** [mtcuison/GhostRider-Android#446]
Gumawa ka ng activity para sa listahan ng mga branches.

**NOTE :Dapat ito ung unang mag intent pag inopen ni user ung Pacita Reward sa navigation menu ng app.**

Capabilities ng Activity_BranchList.

1. Dapat magdisplay lahat ng branches ng guanzon dun sa list.
2. Dapat pwede magsearch si user ng branch.
3. Upon clicking ng specific na branch. Dapat mag display ng Dialog_SelectAction.
4. Dapat mag intent depending sa kung anong action ang selected ni user sa Dialog_SelectAction.

**Comment by ggutoman** [comment]
anong class ang gagamitin ko para maretrieve ang list ng branches? @mikegarcia8748

**Comment by mikegarcia8748** [comment]
sa ngayon ginagawa ko palang ung analysis ng class. isend ko nalang dito ung mga tatawagin mong function @ggutoman

**Comment by mikegarcia8748** [comment]
pakidagdag nalang ung branch name at sa taas ng dialog sir @ggutoman  para alam ni user kung ano ung napindot nya na branch




![Image](https://user-images.githubusercontent.com/76087753/232179728-59b6021f-fbc3-407e-9fbc-e82e50ec7ae3.png)

**Comment by ggutoman** [comment]
okay na ito sir

**Comment by mikegarcia8748** [comment]
Okay na ito
