### ISSUE TITLE
Activity_BranchRate

### ISSUE THREAD

**Issue by mikegarcia8748** [mtcuison/GhostRider-Android#464]

**Comment by mikegarcia8748** [comment]
nagkacrash ung activity_branchrate pagkatapos maopen @ggutoman 

![Image](https://user-images.githubusercontent.com/76087753/232177808-c5f41c30-ee40-4bb7-8139-bbf6b30c3707.png)

**Comment by ggutoman** [comment]
icommit ko nalang po ito ulit. baka may d nasama sa commit

**Comment by ggutoman** [comment]
app crash upon clicking rate buttons, passing null value caused by list data size on getItemCount() of recyclerview adapter for branch rate

**Comment by mikegarcia8748** [comment]
pakilagay sa loob ng asynctask ung SaveBranchRatings.

Check muna kung connected sa internet ung device gamit ung ConnectionUtil na class

![Image](https://user-images.githubusercontent.com/76087753/232365208-6ba25aac-fbce-4984-885e-3743211ea013.png)

**Comment by mikegarcia8748** [comment]
pakicheck ung VMLeaveApplication para may reference ka kung pano mo ilalagay sa loob ng asynctask ung SaveBranchRatings
@ggutoman 


![Image](https://user-images.githubusercontent.com/76087753/232365374-c28351b2-a916-4249-91b1-f8c69a95122d.png)

**Comment by ggutoman** [comment]
okay na ito sir

**Comment by mikegarcia8748** [comment]
Okay na ito
