### ISSUE TITLE
Build Version v.3.016.054 b Issues

### ISSUE THREAD

**Issue by johncarlostacruz** [mtcuison/GhostRider-Android#518]
- [x] #519
![image](https://github.com/mtcuison/GhostRider-Android/assets/23698764/f6fb0809-0010-4d38-bb07-e32e513b667c)

**Comment by mikegarcia8748** [comment]
Mali ung name ng version, Dapat Guanzon Circle v.3.16.054 b kasi un ung nakadeploy ngayon

**Comment by mikegarcia8748** [comment]
Okay na ung issue #519 pwede na i-test sa alpha testing
