### ISSUE TITLE
Integration Testing/Automation Testing

### ISSUE THREAD

**Issue by mikegarcia8748** [mtcuison/GhostRider-Android#521]
Implement instrumentation testing under the Authentication Library

- [ ] #526
- [ ] #527
- [ ] #528
- [ ] #529
- [ ] #530

**Comment by ggutoman** [comment]
![Uploading error commit.JPG…]()

**Comment by mikegarcia8748** [comment]
Hold muna ito kung mahirap. Dun muna tayo sa mga priority

Or sa unit testing muna.

**Comment by mikegarcia8748** [comment]
Automation Testing for android through Instrumentation testing cancelled
