### ISSUE TITLE
Branch Rate Testing 

### ISSUE THREAD

**Issue by mikegarcia8748** [mtcuison/GhostRider-Android#534]
Branch Evaluation/ Gawad Pacita

**Flow ng Project**

1.  Login/Create Account pag wala pang account
2. Open Navigation Drawer
>NOTE: Check the table for xxxAndroidObject and xxxAODeptRole, Dito kasi nakalagay kung ano ung mga authorize users na may access sa Branch Rate.
>NOTE: May mga selected officers/departments na pwedeng gumamit ng branch rate base sa binigay na mechanics ng HR.
3. Tap "Branch Evaluation"
4. List ng mga branches ang unang bubungad sa users sa 1st TAB, 2nd TAB lalabas ung mga recently evaluated branches.
5. To evalaute branch, Tap the selected branch on the list.
6. Once a dialog displayed Tap 'Evalute'.
7. Once na na-tap na ung Item lalabas ung mga criteria para i-evaluate ung branch.
8. Tap 'Pass' or 'Fail' sa bawat criteria para i-evaluate ung branch.
9. Once tapos na ang evaluation, pwede ng i-post ung result.

**NOTES**
- Everytime na nag-eevalute ng branch per criteria nagsesave agad ito sa local data ng device. So kahit maclose ni user ung app may nakasave parin na data para magcontinue.

**RULES**
1. Once lang dapat makakapag rate ng parehong branch.
2. Kung hindi nai-post ang current evaluation ng branch. Magrereset dapat ito sa next day.
3. Pag nagreset ung branch evaluation sa next day, hindi pwedeng irate ng dalawang beses ung branch.
4. Every visit ng officer sa branch. Kailangan i-evaluate ulit.

**MODULES TO TEST**

1. Branch List
>Retrieval of branch list. (tab 1)
>Retrieval of recently evaluated branch (tab 2)
2. Branch Rating
> Import of Pacita_Rules aka criteria for evaluation.
> Display of different criteria base on department/position of the officer.
> Validation sa pag re-evaluate ng same branch.
3. Uploading/Posting
> Validation sa pagpost ng hindi natapos ang evaluation.
4. Recently Evaluations
> Dapat tugma ung laman ng evaluation sa data.
5. Evaluated Branch Records.

Comment below to add test plan.

**Comment by mikegarcia8748** [comment]
Ito po ung mechanics na binigay ng HR para sa Gawad Pacita

https://www.figma.com/file/DrAICTbX0fFTeYudBJ5UY7/Guanzon-Circle-Projects?type=whiteboard&node-id=1-216&t=UeNeXs4eIJw0ZPlm-4

**Comment by johncarlostacruz** [comment]
**Evaluators Account - mag kaiba ang criteria** 

- [ ] CM dept - walang data lumalabas hindi   makapag create ng evaluation.

- [ ] HCM Dept - finish na yung rating unable to   save parin.

- [ ] Area head - unable to find pacita rules.

- [ ] UI, spelling & displays - nag auto fill yung evaluation,  nag scroll up bumabalik sa taas pag nag eevaluate specially sa HCM mahaba kasi yung list nila sa evaluation.

**Comment by mikegarcia8748** [comment]
@johncarlostacruz pahingi ng user id ng mga ginagamit mong accounts.

**Comment by johncarlostacruz** [comment]
SELECT * FROM App_User_Master WHERE sEMailAdd = 'johncarlostacruz@gmail.com'; ito yung ginagamit kung email pinapalitan ko lang ng empolyee ID
SELECT * FROM Client_Master WHERE sCompnyNm LIKE '%cabison%steve%';M00107007513;CM:
SELECT * FROM Client_Master WHERE sCompnyNm LIKE '%chung%jesse%';M03710000439;HCM
SELECT * FROM Client_Master WHERE sCompnyNm LIKE '%natividad%grace%';M00101000217;AREAHEAD

**Comment by mikegarcia8748** [comment]
@johncarlostacruz paprovide ng additional details regarding sa mga reported concern ng testing:

HCM Dept - finish na yung rating unable to save parin.
> Ano error message dito?

Regarding sa concern ng 
- Area head - unable to find pacita rules.
- walang data lumalabas hindi makapag create ng evaluation.
Same lang nagause ng ganitong issue, most probably pag kakainstall mo ng app, or kakaopen mo ng Branch Evaluation at walang naimport na Data ng pacita rules.
Base sa observation, connection issue ang problema.

Fixed na ung last issue

**Comment by johncarlostacruz** [comment]
**Evaluators Account - mag kaiba ang criteria** 

- [ ] CM dept
>evaluation history - hindi lumalabas yung machine and equipment, ratings lumalabas 0 pero may evaluation naman.
![image](https://github.com/mtcuison/GhostRider-Android/assets/23698764/d8f4e96e-6a9d-4251-b9e4-72746f6e95e4)
![image](https://github.com/mtcuison/GhostRider-Android/assets/23698764/9eba57aa-d411-40a7-bddc-42062daedb7f)

- [ ] HCM
>CR and Pantry for MC/Stockroom for MP hindi lumalabas sa evaluation history.
>ratings lumalabas 0 pero may evaluation naman.

- [ ] Area Head
>unable to find pacita rules, sDeptIdx = 015 ang nakalagay sa mga area head, sa may Pacita_Rule sEvaltype = '4' ang nakalagay  pag pinalitan ng 015 lalabas yung pacita rules sa account ni area head.

- [ ] guest officer
>ratings 0 lumalabas pero may evaluation naman.

**Comment by johncarlostacruz** [comment]
- [ ] Area Head
>unable to find pacita rules, sDeptIdx = 015 ang nakalagay sa mga area head, sa may Pacita_Rule sEvaltype = '4' ang nakalagay  pag pinalitan ng 015 lalabas yung pacita rules sa account ni area head.

- [ ] Evaluation History
> sa history lumalabas yung ibang evaluation ng mga department pero pag inopen mo, yung assign na dept na nasa account mo yung lumalabas na naevaluate.
