### ISSUE TITLE
Guanzon Circle v.3.16.056 s QA Testing

### ISSUE THREAD

**Issue by mikegarcia8748** [mtcuison/GhostRider-Android#540]
### Update Quality Assurance Testing

Update for this version includes BUG Fix for the reported issues on #533 and Additional Changes for Authentication

**To Test:**
**BUG FIXES**

**PET Manager**
- [x] Leave Application List
> Nagooverlap ung scrollable UI sa Toolbar, kaya pumapatong ung ibang text/labels sa title.
> Ung mga lumalabas na Leave Application List sa Dashboard ng app pag may mga hindi pa na-aapprove na application. Lumalabas ung Approve/Disapprove button once tinap nila ung application para makita ung full details.

- [x] Leave Approval
> For Associates: hindi dapat lumalabas ung Approve/Disapprove button pag nagview sila ng application nila.
> Once nag-error ung approval ng Leave walang value ung message/null, which ang lumalabas lang sa message dialog ay 'message'.
          
- [x] OB Application List
> Nagooverlap ung scrollable UI sa Toolbar, kaya pumapatong ung ibang text/labels sa title.
> Ung mga lumalabas na OB Application List sa Dashboard ng app pag may mga hindi pa na-aapprove na application. Lumalabas ung Approve/Disapprove button once tinap nila ung application para makita ung full details.

- [x] OB Approval
> For Associates: hindi dapat lumalabas ung Approve/Disapprove button pag nagview sila ng application nila.
         - [ ] a. Employee_Timesheet table. to update timesheet kapag nagapprove ng OB

- [x] Selfie Log
> Hindi working ung resend button sa list ng mga selfie. - Reported by sir Jed.
> Nag-eerror ung part ng validation ng selected branch kaya hindi napapalitan. - Reported by ma'am Queen.
No solutions Yet.
Actions Done:
> Added Firebase Error Reporting sa part ng mga modules affected ng mga reported concerns, para matrace kung paano nagkaka-error through firebase crashlytics.

**Credit Online Application**
- [x] Branch Application List
> Mali ung Date Sent, Date Approve.
>Actions Done: Tinaggal nalang ung mga nabanggit na date. Hindi kasi ito kasama sa data ng Branch Application List pero kasama ito sa User Application List.
- [x] User Application List
> Dinagdag ung Date Sent at Date Approved.

**ADDITIONAL CHANGES**

**Authentication**
> What's new?
> This authentication was just migrated from a Fragment Component inside an activity to Individual Activity.
> This migration also includes the Integration(Automation) testing as part of the research of Android Team.
- [x] Login
- [x] Create Account
- [x] Forgot Password

**Comment by johncarlostacruz** [comment]
**PET Manager**
- [ ] Leave Application List
> Nagooverlap ung scrollable UI sa Toolbar, kaya pumapatong ung ibang text/labels sa title.

- [ ] Leave Approval
> pag na click na yung approve button yung message box na lalabas "message" na word lang yung nakalagay .
> Employee_Timesheet table. hindi nag aupdate kapag nagapprove ng leave.

- [ ] OB Application List
> Nagooverlap ung scrollable UI sa Toolbar, kaya pumapatong ung ibang text/labels sa title.
> Lumalabas ung Approve/Disapprove button once tinap nila ung application para makita ung full details na nasa dashboard.

- [ ] OB Approval
> For Associates: hindi dapat lumalabas ung Approve/Disapprove button pag nagview sila ng application nila.
> Employee_Timesheet table. hindi nag aupdate kapag nagapprove ng OB.


**Credit Online Application**
- [ ] Loan Application
> employment info - job title tinatangap nya kahit free text ang nilagay 
>sEmployer pumupunta sa sposition

**Comment by johncarlostacruz** [comment]
**PET Manager**

- [ ] OB Approval
>Employee_Timesheet table. hindi nag aupdate kapag nagapprove ng OB.

- [ ] Loan Application
>employment info - job title tinatangap nya kahit free text ang nilagay.

**Comment by mikegarcia8748** [comment]
Regarding sa concern ng OB Approval na hindi naguupdate, nag eerror ba dun sa app pag nag aapprove?

Loan Application, Fixed na ito para sa next update, kailangan nalang ng another closed testing para madouble check.

**Comment by johncarlostacruz** [comment]
hindi ko alam pero delay yung update nya naayos na sya
![image](https://github.com/mtcuison/GhostRider-Android/assets/23698764/98b3a193-b3b5-470e-9e76-75e92959c6b9)

**Comment by johncarlostacruz** [comment]
- [ ] Loan Application Entry
>SELECT  *FROM `Credit_Online_Application` WHERE sClientNm LIKE '%afalla%josep%';
nag sisave sa data yung space sa pangalan example "Afalla , Josephine  cafirma "

**Comment by mikegarcia8748** [comment]
wag mo nalang isama ung mga bagong reported na bug dito sa issue ng version na tinetest kasi hindi na makakapag update ng app, kung lahat ng marereport na bug kailangan isama sa iisang update.

**Comment by johncarlostacruz** [comment]
OB and  Approval,  Loan Application Entry issues ginawan na ng separate issue..
