### ISSUE TITLE
Guanzon Circle v3.16.057.063s

### ISSUE THREAD

**Issue by johncarlostacruz** [mtcuison/GhostRider-Android#551]
- [x] Login
>sUsername field sa may App_user_Master nag kakaroon ng Null sa suffix name.
>hindi nag sesend sa email yung verification.

- [x] Credit Online Application
>other barangay sa credit online application entry nag iinvalid, please enter barangay yung lumalabas.
>SELECT *FROM Credit_Online_Application WHERE sClientNm LIKE '%afalla%josep%';
nag sisave sa data yung space sa dulo ng pangalan example "Afalla , Josephine cafirma ".

**Comment by mikegarcia8748** [comment]
Ung issue ng Login solve na sa #549 si @ggutoman ang nag-ayos

**Comment by mikegarcia8748** [comment]
>nag sisave sa data yung space sa dulo ng pangalan example "Afalla , Josephine cafirma ".

Paki-check ung version ng android app nito, dati ng naayos ung issue nito.

**Comment by mikegarcia8748** [comment]
@johncarlostacruz follow-up ito kung okay na paki-close nalang. Thanks

**Comment by johncarlostacruz** [comment]
- [ ] Login
>ito lumalabas pag nag crecreate ng account
![image](https://github.com/mtcuison/GhostRider-Android/assets/23698764/684751c8-83ba-4523-82b6-3612190e9863)
>hindi nag sesend ng verification sa email

**Comment by johncarlostacruz** [comment]
- [ ] inquiries
ganito lumalbas na message pag open ng inquiries
![image](https://github.com/mtcuison/GhostRider-Android/assets/23698764/d61facd7-d361-4a5e-a8dc-aac0cbf9e88d)

**Comment by mikegarcia8748** [comment]
promoted na sa production ung updated version para sa concern na ito
