### ISSUE TITLE
Credit Online Application No Model ID

### ISSUE THREAD

**Issue by mikegarcia8748** [mtcuison/GhostRider-Android#556]
Paki-check ung Credit Online Application.

Base dito sa reported concern walang Model ID na nagse-save sa Credit_Online_Application.
>Select * from Credit_Online_Application WHEre sTransNox IN ('D3NUM2300012', '42PB23000008', 'C0YNZ2300036', 'CI4SY2300111', 'CI4TJ2300074', 'C0ZYK2300129');

**Troubleshoot:**
Dun palang sa Introductory Question i-check mo na kung may mag-sesave ba na sModelD sa data na pinapasa, tapos before sa saving ng entry icheck mo rin ung data ng local (Credit_Application).

**Comment by jeitee** [comment]
upon testing working na ito sa GRider_Dev na branch. Ung date ng mga entry sa mga query nung nacheck ito pa ung dating code na ang nakukuha palang na data is ung brand.

DONE.
